services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    container_name: grafana

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    container_name: node-exporter

volumes:
  prometheus_data:
  grafana_data: